<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Backround_model extends CI_Model
{

    public $table = 'backround';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    public function get_all_backround($search){
        $query = $this->db->query("SELECT * FROM backround WHERE n_backround LIKE '%$search%'");
        $result = $query->num_rows;

        $json = [];

        if ( $result > 0 ){

            while ( $rows = $query->fetch_assoc() ) {
                $json[] = ['id' => $rows['id'],'text' => $rows['n_backround']];
            }
        }
        else{

            $json[] =  array('id' => '', 'text' => 'No results found...');

        }
        return $json;
    }

    // get all
    function get_br()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result_array();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('n_backround', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('n_backround', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Backround_model.php */
/* Location: ./application/models/Backround_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-28 08:50:18 */
/* http://harviacode.com */